dev: true
project_name: 'contactlist'
digInUrl: '/app/contactList'

connection:
  port: 5001
  host: localhost

sms:
  twilio:
    sid: ''
    token: ''
    number: ''

nav:
  - name: 'Message Sent'
    path: '/app/messagesSent'
  - name: 'Contact List'
    path: '/app/contactList'