dev: true
project_name: 'contactlist'
digInUrl: '/app/contactList'

connection:
  port: 5002
  host: localhost

sms:
  twilio:
    sid: 'AC80e37a7de97f05a8d11eb0a6e199b7b4'
    token: 'de92c59a9446b75c7f19556d2acdb93d'
    number: '+16106150459'

nav:
  - name: 'Message Sent'
    path: '/app/messagesSent'
  - name: 'Contact List'
    path: '/app/contactList'